### ISSUE TITLE
LDAP support

### ISSUE THREAD

**Issue by helmut72** [stalwartlabs/jmap-server#11]
Would be great if jmap-server supports LDAP auth and reading user, group, mailinglist and maybe domain information from LDAP. It should also support other attribute than only `mail` to get user aliases. For example `otherMailbox` is common for aliases.

Thank you.

**Comment by dumblob** [comment]
@downtownallday might be of interest for you in some distant future :wink:.

**Comment by mdecimus** [comment]
Stalwart JMAP v0.3 now supports LDAP authentication.

**Comment by helmut72** [comment]
Thanks a lot! Time to test it again. I hope I use the right repo, because there is now also mail-server repo.

**Comment by mdecimus** [comment]
Unless you are planning to run Stalwart on multiple servers, I'd recommend to use the all-in-one mail server.
