### ISSUE TITLE
Feature request: Allow setting the (initial) admin password via environment variable

### ISSUE THREAD

**Issue by Lykos153** [stalwartlabs/jmap-server#13]
I'm currently setting everything up in a k8s cluster and I would like to get it up and running without either briefly exposing the admin account to the public or having a manual step between deploying the server and exposing it.

On a similar note, is there already a mechanism in place to reset a forgotten admin password? If not, this could be tackled in conjunction.

**Comment by mdecimus** [comment]
I probably forgot to document this but it is possible to reset the admin password using the ``stalwart-jmap`` binary as follows:

```bash
stalwart-jmap --set-admin-password <NEW_PASS>
```

Setting the admin password via an environment variable should be quite simple to implement, so I'll leave this issue open. However please note that each time the container is restarted it would reset the admin password as long as the environment variable is present.

**Comment by Lykos153** [comment]
Thank you, that already helps. However, setting the password via the environment would be great because using a password in a command line makes it visible to other processes through the process table.

**Comment by mdecimus** [comment]
Actually, I took a look at the code and it is currently possible to set the admin password using the ``SET_ADMIN_PASSWORD`` environment variable and also from the YAML config file. If it is a brand new setup, the admin account is created with this password. If the admin account already exists, the password is changed and the JMAP server exits.

**Comment by mildred** [comment]
I added this to my systemd unit, that will update the password only the first time:

```desktop
ExecStartPre=/bin/sh -c ' \
  file=/var/lib/stalwart-jmap/admin-password-init-ok; \
  export SET_ADMIN_PASSWORD=XXXXXXXXXXXX; \
  set -x; \
  test -e $$file && exit 0; \
  set -e; \
  /usr/local/bin/stalwart-jmap \
  --config=/etc/stalwart-jmap.yml \
  --db-path=/var/lib/stalwart-jmap/ \
  --log-level=info; \
  touch $$file; \
  '
```

**Comment by mdecimus** [comment]
Account management in Stalwart JMAP v0.3 is now handled by an external directory so I believe this is no longer necessary.
