### ISSUE TITLE
Corrupted data: Failed to decode part error

### ISSUE THREAD

**Issue by rudihorn** [stalwartlabs/jmap-server#16]
I'm not entirely sure how this happened, but I was moving and sorting mail around using the TMail web app, and somehow this has resulted in one of the messages (and/or mailboxes) being corrupted. 

The log contains an error message:

```
ERROR jmap::error::method: JMAP request failed: DataCorruption("Failed to decode part for 2/39999.")
```

If I recall correctly there was one message which I tried moving and which failed to move folders even after multiple tries.

Are there any pointers on how to potentially find and fix/remove the corrupted data?

**Comment by mdecimus** [comment]
Hi,

I checked where this error is triggered and it is related to a decoding issue while displaying the message preview, not an actual data corruption even though the error message was grouped in that category. The ID of the message that is causing this error is ``bhb3`` (which is 39999 encoded in base32). 

In case this mailbox does not contain any private/sensitive information, could you compress the database and send it to me so I identify the problem and send you a fix? Or alternatively I can write a command line tool to dump the contents of the database to a text file to see what went wrong with that message.

Thanks.

**Comment by rudihorn** [comment]
Unfortunately the mailbox does contain private information, but if it is possible to dump some data I could sift through it and try finding what the exact underlying issue is. Or if you have any other ideas on how I could debug the contents of the database.

Thanks!

**Comment by mdecimus** [comment]
I have the ``export`` tool ready, you can download the x86 binaries from [this link](https://github.com/stalwartlabs/jmap-server/files/9869259/debug-tools.tar.gz) or if you prefer compiling it directly from the sources, the export tool is now available on the ``master`` branch.

To dump the contents of that message execute:

```
./export --db-path <PATH_TO_DB> --account-id 2 --document-id 39999 >> dump.txt
```

The dump.txt file will include all the message metadata as well as the message contents, if you could send that to me it would be great.

Also, the version now in master (also included in the tar.gz along with export) will let you keep accessing your messages even if that one failed to decode. It is a debug build so it will be much slower and the LMTP module is disabled, but it is a temporary fix until I identify what went wrong with that message.

Thanks you.

**Comment by rudihorn** [comment]
Thank you very much for the debug tool!

I had a closer look and the problem seemed to be that `MessagePart::decode` was broken for empty message parts. This particular email had a text part and an HTML part, where the text part had zero length. This bug should already be fixed by https://github.com/stalwartlabs/jmap-server/commit/976c1fc5fea3ca314ad7dabf2be18aff58e6ab86#diff-906caac73e74d8b24b80238b41ed2ba3afbdbf2131dc39813d19937bc32fe9ae, though it would be nice if this issue could be left open until the next release just so I can confirm it is properly fixed then (I have not tried the master branch binaries you have posted yet).

I am wondering if it is worth changing the code to use the HTML part to compute the preview, but this is not as serious. Everything else seemed to be fine in the message.

**Comment by mdecimus** [comment]
Glad to hear that you spotted the problem!

Version 0.2.0 with Sieve support should be released during this week. If possible, could you upload to this issue the message (removing any private content) that was triggering this error? That way I can add it to the test suite and make sure this is fixed in the next release.

Thanks!

**Comment by rudihorn** [comment]
[dump_test.txt](https://github.com/stalwartlabs/jmap-server/files/9932759/dump_test.txt)

Here is a dump of a reproduction mail which causes the same error. I see the release is out now (thanks for this!), is the correct / safe way to upgrade to just run the same installation bash line?

**Comment by mdecimus** [comment]
Thanks for the dump! I'll check it out shortly, but v0.2 should no longer fail if a part can't be decoded.
To upgrade you can replace the ``stalwart-jmap`` binary directly, it can be download from the [releases page](https://github.com/stalwartlabs/jmap-server/releases/tag/v0.2.0).

**Comment by mdecimus** [comment]
Hi @rudihorn , may I mark this issue as fixed?

**Comment by rudihorn** [comment]
Hi @mdecimus,

sorry for the delay. Yes I can confirm it is fixed now and you can close this issue.

Thanks!
