### ISSUE TITLE
"Identity/get" not returning email address?

### ISSUE THREAD

**Issue by zvasilev** [stalwartlabs/jmap-server#23]
Hello Mauro,

First just to say I'm glad that the JMAP ecosystem is starting to take off.
I've just installed the server on my machine and started integrating an iOS app (mailtemi.com).

My first goal is to make client and server interoperable with Basic Auth.
And after that to add OAuth support.

My setup is to install the jmap server behind nginx proxy.
A test user was created successfully.

```

+------------------+---------------+-------------+-------+
| E-mail           | Name          | Description | Quota |
+------------------+---------------+-------------+-------+
| admin            | Administrator |             |       |
+------------------+---------------+-------------+-------+
| test@mailtemi.eu | test          |             |       |
+------------------+---------------+-------------+-------+

```

The attached files are the responses from the first API calls.
.well-known/jmap
-> session0
{apiUrl}/{Identity/get}
{apiUrl}/{PushSubscription/get}
{apiUrl}/{Mailbox/get}
   -> session1

From {Identity/get} the minimum expected response is to have the user emails.
FastMail server returns it but here the response is empty.

Any hint on what is wrong or incorrectly setup will be very welcome.
Thanks,
- Zhivko
[session0.txt](https://github.com/stalwartlabs/jmap-server/files/10253886/session0.txt)
[session1.txt](https://github.com/stalwartlabs/jmap-server/files/10253887/session1.txt)

**Comment by mdecimus** [comment]
Hi Zhivko,

I'm glad to hear that you are working on integrating Mailtemi with Stalwart JMAP!

Regarding your question, identities need to be created first before they can appear on the response list. This can be done by users directly (as long as the specified email address matches the system address) and does not require involvement from the system administrator. Perhaps on your client app you can ask users if they want to create an identity in case none is found?
In any case, I'll keep this issue open for Stalwart JMAP v0.3 as it is a good idea that a default identity is created when the account is created.


Cheers,
Mauro

**Comment by mzch** [comment]
I have a question. Before using Stalwart-JMAP server, must users create their idenities? How do they finish it? I can't find such an operation in your document...

**Comment by mdecimus** [comment]
@mzch Identities have to be created by the JMAP client but the next version will automatically create the default identity for users. In any case, JMAP clients should allow users to create additional identities (for example, to use aliases or different signtures).

**Comment by mzch** [comment]
Well, I see. Thanks @mdecimus !

**Comment by kri164** [comment]
This bug was closed without any code commit? How is it fixed?
