### ISSUE TITLE
Implement domain wildcard aliases

### ISSUE THREAD

**Issue by mildred** [stalwartlabs/jmap-server#27]
It seems there is no way to catch all mails from a domain to a given e-mail address like generally done with wildcard aliases. I believe it ought to be implemented.

A simple implementation could be to have the `@example.org` alias mean every e-mail for `example.or`. If the first alias search fails with the full e-mail address, then the local-part can be removed and the search could be performed with only `@domain_part`.

### Discussed in https://github.com/stalwartlabs/jmap-server/discussions/26

<div type='discussions-op-text'>

<sup>Originally posted by **mildred** December 29, 2022</sup>
Just a simple question because the docs does not talk about it. is there a way to make a catch-all alias to collect every mail for a domain?

Thank you</div>

**Comment by mildred** [comment]
Also, generally adding a `+` and a suffix to the local part is ignored in mail servers, it could be nice to implement that as well.

`tol+foo@example.org` would be matched against the `tom@example.org` account.

**Comment by mdecimus** [comment]
Hi @mildred 

Thanks for the suggestion. Catch-all and address suffixes will definitely be included in version 0.3 of Stalwart JMAP.

**Comment by mildred** [comment]
This might not be so important as I think with a proper SMTP front-end aliases can be configured there instead. However you need a separate user database with user info, or redirect every e-mail from unknown accounts on a domain to predetermined `catchall@domain.example.org` address after querying the stalwart user database. Hence my need for https://github.com/stalwartlabs/jmap-server-cli/issues/5

**Comment by mildred** [comment]
I implemented it in the frontend SMTP server (exim). I developped a small gateway that will look up the recipient address and if not found will look up for an address `*@domain.example.org` (yes a `*` is a valid local) using the stalwart JMAP API. This works well.

https://github.com/mildred/stalwart-gw/blob/b609a612dc86b6fd93799e42d613e6786947b375/src/jmap.nim#L105
