### ISSUE TITLE
Provide a way to fetch DKIM private key

### ISSUE THREAD

**Issue by mildred** [stalwartlabs/jmap-server#32]
To be able to have a single place where the DKIM private key is stored, and to have a way to sign DKIM outside of stalwart (I set up an Exim instance dedicated for submission to be paired with stalwart-imap for legacy clients that do not support jmap, and it needs to be able to sign using DKIM), we would need a way to fetch the DKIM secret key for a domain using the API and the admin credentials.

**Comment by mildred** [comment]
Here, the secret of Principal/get is always set to null it seems:

https://github.com/stalwartlabs/jmap-server/blob/87cc39c3cf21daabc93c170574f5839c0cfdc539/components/jmap_sharing/src/principal/get.rs#L84

**Comment by mdecimus** [comment]
Hi, support for retrieving private keys or passwords is not allowed for security reasons. You should store your private key in both places.

**Comment by mildred** [comment]
Perhaps in the same idea as the IMAP server that is a proxy for JMAP, a submission-only SMTP server could proxy for JMAP submission.

    submission-proxy -> jmap (with DKIM signing) -> MTA -> internet
