### ISSUE TITLE
smtp server

### ISSUE THREAD

**Issue by mispp** [stalwartlabs/jmap-server#38]
from reddit:

> Yes, the plan is to release an SMTP server and have a completely integrated mail server solution.

is this still the plan? there seems to be a drop in activity in commits here

**Comment by mdecimus** [comment]
> is this still the plan? there seems to be a drop in activity in commits here

Yes, the SMTP server is now ready but it will be released as soon as the documentation is completed (hopefully in about 2 weeks). As soon as the SMTP server is released a code refactoring of the JMAP and SMTP servers is planned.
