### ISSUE TITLE
[Feature] Suspending accounts and/or domains

### ISSUE THREAD

**Issue by JABirchall** [stalwartlabs/jmap-server#44]
There is currently no method (from what ive read) to suspend an account from sending emails. So i've submitted this as more of a tracker for interest and feedback.

There are times when an account needs to be suspended for example, IF, the account is comprimised, spamming, received to many bounces, received to many complains, submitted to a blacklist, or based on the admins discretion. 

In the event an account is suspended the account **can not**:
- Login
- Send email from their address
- Send email to a mailing list
- Send email from a group

The account should only be able to receive emails to be available when the account unsuspended. 

The same for a domain but more broad.
If a domain is suspended, all accounts under that domain is suspended. 

Proposed signature from CLI

```
stalwart-cli account update [EMAIL] --suspend=true # Suspend a account
stalwart-cli account update [EMAIL] --suspend=false # Unsuspend the account
stalwart-cli domain update [DOMAIN] --suspend=true # Suspend a domain
stalwart-cli domain update [DOMAIN] --suspend=false # Unsuspend the domain
```

**Comment by mdecimus** [comment]
Hi, I am currently refactoring the JMAP server code base and in the new version all authentication will be delegated to either LDAP or SQL. You will be able to suspend accounts directly from your database.

**Comment by mdecimus** [comment]
Hi @JABirchall , Stalwart JMAP v0.3 now uses an external directory for authentication and this feature is now supported. Closing the PR.
