### ISSUE TITLE
Stalwart JMAP server not sending emails through Stalwart SMTP. 

### ISSUE THREAD

**Issue by mjac1521** [stalwartlabs/jmap-server#45]
My setup was working perfect I was able before to send and receive emails using jmap and the smtp server but for some reason now I can only receive emails. When I try to send an email from a jmap client it behave normally in the client but email never reach the destination no even show in Stalwart SMTP logs.

Sincerely Maykel

**Comment by mdecimus** [comment]
Try setting the log level to DEBUG and check if anything useful appears on the logs. If you are still having problems please start a new Discussion instead.
