### ISSUE TITLE
[enhancement]: Enable Cors and cors-related configuration

### ISSUE THREAD

**Issue by Nemolo** [stalwartlabs/jmap-server#52]
### Which feature or improvement would you like to request?

It would be nice to have support for CORS in JMAP APIs.

### Is your feature request related to a problem?

This would allow for example the testing of the server with the [demo](https://jmap.io/jmap-demo-webmail/) provided by jmap.io.
This would also allow the development and usage of third party Web Clients with StalwartLabs JMAP server.

At the moment i fixed a workaround with an NGINX Proxy, but it would be nice to have a specific option to handle it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mdecimus** [comment]
Thanks, support for user-defined HTTP headers will be included on the release scheduled for the end of this week.

**Comment by mdecimus** [comment]
Version [0.3.4](https://github.com/stalwartlabs/mail-server/releases/tag/v0.3.4) has just been released adding this feature and the documentation has been [updated](https://stalw.art/docs/jmap/overview#http-headers). To upgrade just replace the binary.

**Comment by Nemolo** [comment]
Hello, i tested the new version and i still see an issue: Prelights request (OPTIONS) will return 404, triggering a browser error on fetch.
I sticked with the Nginx Proxy. Here is the configuration that i used:
```
location / {
     if ($request_method = 'OPTIONS') {
        add_header 'Access-Control-Allow-Origin' '*';
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS';
        add_header 'Access-Control-Allow-Headers' 'Authorization';
        add_header 'Access-Control-Max-Age' 1728000;
        add_header 'Content-Type' 'text/plain; charset=utf-8';
        add_header 'Content-Length' 0;
        return 204;
     }
     proxy_set_header Host $host;
     proxy_set_header X-Real-IP $remote_addr;
     proxy_pass https://xxx:8080;
}
```
and on the config.toml:
```
[jmap.http]
headers = ["Access-Control-Allow-Origin: *", "Access-Control-Allow-Methods: GET, POST, OPTIONS", "Access-Control-Allow-Headers: Authorization"]
```

**Comment by mdecimus** [comment]
Hi, support for `OPTIONS` HTTP requests has now been added and will be included in the next release.

**Comment by mdecimus** [comment]
Support for the `OPTIONS` method was added to version `0.3.5` which was released yesterday.
