### ISSUE TITLE
[bug]: "Email/import" doesn't change the state

### ISSUE THREAD

**Issue by zvasilev** [stalwartlabs/jmap-server#58]
### What happened?

I have created an automated test in which two app instances run on one account. In this test, app1 imports emails into different folders or changes email properties (read/unread/etc.), and the other app syncs and checks that they are okay.

However, it seems that "Email/import" doesn't change the state. As a result, the sync from the other app instance cannot detect the changes.

Please attach the Stalwart and Fastmail request/responses.
[stalwart_request.json](https://github.com/stalwartlabs/jmap-server/files/13332295/stalwart_request.json)
[stalwart_resp.json](https://github.com/stalwartlabs/jmap-server/files/13332296/stalwart_resp.json)
[fastmail_request.json](https://github.com/stalwartlabs/jmap-server/files/13332305/fastmail_request.json)
[fastmail_resp.json](https://github.com/stalwartlabs/jmap-server/files/13332306/fastmail_resp.json)

### How can we reproduce the problem?

I can reproduce the problem by doing the following steps:

### Version

v0.4.x

### What database are you using?

SQLite

### What blob storage are you using?

Local

### Where is your directory located?

None

### What operating system are you using?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mdecimus** [comment]
I am currently refactoring the message store and I wasn't able to reproduce this problem on the new backend. I'll let you know once the new version is released, hopefully in 2 or 3 weeks.

**Comment by zvasilev** [comment]
work fine in v0.5.x
