### ISSUE TITLE
Filtering with Sieve and other methods

### ISSUE THREAD

**Issue by mdecimus** [stalwartlabs/jmap-server#7]

**Comment by helmut72** [comment]
Would be great if it supports Sieve to make it work with Roundcube, Thunderbird or SOGo.

**Comment by mdecimus** [comment]
> Would be great if it supports Sieve to make it work with Roundcube, Thunderbird or SOGo.

Sieve support is the next item on the roadmap.

**Comment by mdecimus** [comment]
JMAP for Sieve support added to v0.2.0.
